//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Record", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCF_Client.ServiceReference1.Kutya))]
    public partial class Record : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kutya", Namespace="http://schemas.datacontract.org/2004/07/Server")]
    [System.SerializableAttribute()]
    public partial class Kutya : WCF_Client.ServiceReference1.Record {
        
        private byte EletkorField;
        
        private string FajtaField;
        
        private string GazdiField;
        
        private byte LabakSzamaField;
        
        private System.Nullable<bool> NemeField;
        
        private string NevField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte Eletkor {
            get {
                return this.EletkorField;
            }
            set {
                if ((this.EletkorField.Equals(value) != true)) {
                    this.EletkorField = value;
                    this.RaisePropertyChanged("Eletkor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Fajta {
            get {
                return this.FajtaField;
            }
            set {
                if ((object.ReferenceEquals(this.FajtaField, value) != true)) {
                    this.FajtaField = value;
                    this.RaisePropertyChanged("Fajta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Gazdi {
            get {
                return this.GazdiField;
            }
            set {
                if ((object.ReferenceEquals(this.GazdiField, value) != true)) {
                    this.GazdiField = value;
                    this.RaisePropertyChanged("Gazdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte LabakSzama {
            get {
                return this.LabakSzamaField;
            }
            set {
                if ((this.LabakSzamaField.Equals(value) != true)) {
                    this.LabakSzamaField = value;
                    this.RaisePropertyChanged("LabakSzama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> Neme {
            get {
                return this.NemeField;
            }
            set {
                if ((this.NemeField.Equals(value) != true)) {
                    this.NemeField = value;
                    this.RaisePropertyChanged("Neme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nev {
            get {
                return this.NevField;
            }
            set {
                if ((object.ReferenceEquals(this.NevField, value) != true)) {
                    this.NevField = value;
                    this.RaisePropertyChanged("Nev");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaGetCS", ReplyAction="http://tempuri.org/IService1/EgyKutyaGetCSResponse")]
        WCF_Client.ServiceReference1.Kutya EgyKutyaGetCS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaGetCS", ReplyAction="http://tempuri.org/IService1/EgyKutyaGetCSResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya> EgyKutyaGetCSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaGet", ReplyAction="http://tempuri.org/IService1/EgyKutyaGetResponse")]
        WCF_Client.ServiceReference1.Kutya EgyKutyaGet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaGet", ReplyAction="http://tempuri.org/IService1/EgyKutyaGetResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya> EgyKutyaGetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaPost", ReplyAction="http://tempuri.org/IService1/EgyKutyaPostResponse")]
        WCF_Client.ServiceReference1.Kutya EgyKutyaPost();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaPost", ReplyAction="http://tempuri.org/IService1/EgyKutyaPostResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya> EgyKutyaPostAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaPostCS", ReplyAction="http://tempuri.org/IService1/EgyKutyaPostCSResponse")]
        WCF_Client.ServiceReference1.Kutya EgyKutyaPostCS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaPostCS", ReplyAction="http://tempuri.org/IService1/EgyKutyaPostCSResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya> EgyKutyaPostCSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KutyakListaja", ReplyAction="http://tempuri.org/IService1/KutyakListajaResponse")]
        WCF_Client.ServiceReference1.Kutya[] KutyakListaja();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KutyakListaja", ReplyAction="http://tempuri.org/IService1/KutyakListajaResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya[]> KutyakListajaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KutyakListajaCS", ReplyAction="http://tempuri.org/IService1/KutyakListajaCSResponse")]
        WCF_Client.ServiceReference1.Kutya[] KutyakListajaCS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/KutyakListajaCS", ReplyAction="http://tempuri.org/IService1/KutyakListajaCSResponse")]
        System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya[]> KutyakListajaCSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaAddCS", ReplyAction="http://tempuri.org/IService1/EgyKutyaAddCSResponse")]
        string EgyKutyaAddCS(WCF_Client.ServiceReference1.Kutya kutya);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaAddCS", ReplyAction="http://tempuri.org/IService1/EgyKutyaAddCSResponse")]
        System.Threading.Tasks.Task<string> EgyKutyaAddCSAsync(WCF_Client.ServiceReference1.Kutya kutya);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaAdd", ReplyAction="http://tempuri.org/IService1/EgyKutyaAddResponse")]
        string EgyKutyaAdd(WCF_Client.ServiceReference1.Kutya kutya);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EgyKutyaAdd", ReplyAction="http://tempuri.org/IService1/EgyKutyaAddResponse")]
        System.Threading.Tasks.Task<string> EgyKutyaAddAsync(WCF_Client.ServiceReference1.Kutya kutya);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WCF_Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF_Client.ServiceReference1.IService1>, WCF_Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Client.ServiceReference1.Kutya EgyKutyaGetCS() {
            return base.Channel.EgyKutyaGetCS();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya> EgyKutyaGetCSAsync() {
            return base.Channel.EgyKutyaGetCSAsync();
        }
        
        public WCF_Client.ServiceReference1.Kutya EgyKutyaGet() {
            return base.Channel.EgyKutyaGet();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya> EgyKutyaGetAsync() {
            return base.Channel.EgyKutyaGetAsync();
        }
        
        public WCF_Client.ServiceReference1.Kutya EgyKutyaPost() {
            return base.Channel.EgyKutyaPost();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya> EgyKutyaPostAsync() {
            return base.Channel.EgyKutyaPostAsync();
        }
        
        public WCF_Client.ServiceReference1.Kutya EgyKutyaPostCS() {
            return base.Channel.EgyKutyaPostCS();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya> EgyKutyaPostCSAsync() {
            return base.Channel.EgyKutyaPostCSAsync();
        }
        
        public WCF_Client.ServiceReference1.Kutya[] KutyakListaja() {
            return base.Channel.KutyakListaja();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya[]> KutyakListajaAsync() {
            return base.Channel.KutyakListajaAsync();
        }
        
        public WCF_Client.ServiceReference1.Kutya[] KutyakListajaCS() {
            return base.Channel.KutyakListajaCS();
        }
        
        public System.Threading.Tasks.Task<WCF_Client.ServiceReference1.Kutya[]> KutyakListajaCSAsync() {
            return base.Channel.KutyakListajaCSAsync();
        }
        
        public string EgyKutyaAddCS(WCF_Client.ServiceReference1.Kutya kutya) {
            return base.Channel.EgyKutyaAddCS(kutya);
        }
        
        public System.Threading.Tasks.Task<string> EgyKutyaAddCSAsync(WCF_Client.ServiceReference1.Kutya kutya) {
            return base.Channel.EgyKutyaAddCSAsync(kutya);
        }
        
        public string EgyKutyaAdd(WCF_Client.ServiceReference1.Kutya kutya) {
            return base.Channel.EgyKutyaAdd(kutya);
        }
        
        public System.Threading.Tasks.Task<string> EgyKutyaAddAsync(WCF_Client.ServiceReference1.Kutya kutya) {
            return base.Channel.EgyKutyaAddAsync(kutya);
        }
    }
}
