// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModelToDatabase.Data;

namespace ModelToDatabase.Migrations
{
    [DbContext(typeof(MyDatabaseContext))]
    [Migration("20221109095902_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ModelToDatabase.Models.VideoGames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ar")
                        .HasColumnType("int");

                    b.Property<string>("Besorolas")
                        .HasColumnType("text");

                    b.Property<string>("Kategoria")
                        .HasColumnType("text");

                    b.Property<bool>("Megjelenes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nev")
                        .HasColumnType("text");

                    b.Property<string>("Statusz")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");
                });
#pragma warning restore 612, 618
        }
    }
}
